import Head from "next/head";
import AttendanceConfig from "../components/attendanceconfig";
import styles from "../styles/Home.module.css";
import { get_storyblok } from "../lib/storyblok-integration";

import { useStoryblokState } from "@storyblok/react";

export default function Attendance({story}) {
  story = useStoryblokState(story);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <AttendanceConfig blok={story.content}/>
    </div>
  );
}

export async function getStaticProps() {
  
  let data = await get_storyblok()

  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600, // revalidate every hour
  };
}
